import 'package:flutter/material.dart';
import 'package:invoice/config/app_sizes.dart';

SizedBox height2 = SizedBox(height: 2.scale);
SizedBox height3 = SizedBox(height: 3.scale);
SizedBox height4 = SizedBox(height: 4.scale);
SizedBox height5 = SizedBox(height: 5.scale);
SizedBox height7 = SizedBox(height: 7.scale);
SizedBox height10 = SizedBox(height: 10.scale);
SizedBox height12 = SizedBox(height: 12.scale);
SizedBox height15 = SizedBox(height: 15.scale);
SizedBox height20 = SizedBox(height: 20.scale);
SizedBox height25 = SizedBox(height: 25.scale);
SizedBox height30 = SizedBox(height: 30.scale);
SizedBox height35 = SizedBox(height: 35.scale);
SizedBox height40 = SizedBox(height: 40.scale);
SizedBox height45 = SizedBox(height: 45.scale);
SizedBox height46 = SizedBox(height: 46.scale);
SizedBox height50 = SizedBox(height: 50.scale);
SizedBox height55 = SizedBox(height: 55.scale);
SizedBox height60 = SizedBox(height: 60.scale);
SizedBox height65 = SizedBox(height: 65.scale);
SizedBox height70 = SizedBox(height: 70.scale);
SizedBox height80 = SizedBox(height: 80.scale);
SizedBox height85 = SizedBox(height: 85.scale);
SizedBox height90 = SizedBox(height: 90.scale);
SizedBox height100 = SizedBox(height: 100.scale);

SizedBox width2 = SizedBox(width: 2.scale);
SizedBox width3 = SizedBox(width: 3.scale);
SizedBox width5 = SizedBox(width: 5.scale);
SizedBox width10 = SizedBox(width: 10.scale);
SizedBox width15 = SizedBox(width: 15.scale);
SizedBox width20 = SizedBox(width: 20.scale);
SizedBox width25 = SizedBox(width: 25.scale);
SizedBox width30 = SizedBox(width: 30.scale);
SizedBox width40 = SizedBox(width: 40.scale);
SizedBox width50 = SizedBox(width: 50.scale);
SizedBox width60 = SizedBox(width: 60.scale);
SizedBox width70 = SizedBox(width: 70.scale);
SizedBox width80 = SizedBox(width: 80.scale);
SizedBox width90 = SizedBox(width: 90.scale);
SizedBox width100 = SizedBox(width: 100.scale);
SizedBox width200 = SizedBox(width: 100.scale);
