class Strings {
  static const String skfoods = 'SK Foods';
  static const String date = 'Date';
  static const String companyName = 'Company Name';
  static const String address = 'Address';
  static const String pincode = 'Pincode';
  static const String enterCompanyName = 'Enter Company Name';
  static const String enterAddress = 'Enter Address';
  static const String enterPincode = 'Enter Pincode';
  static const String enterBankName = 'Enter Bank Name';
  static const String enterName = 'Enter Name';
  static const String enterAccountNumber = 'Enter Account Number';
  static const String enterItemName = 'Enter Item Name';
  static const String enterQty = 'Enter quantity';
  static const String enterRateInRuppees = 'Enter rate in ruppees';
  static const String add = 'Add';
  static const String update = 'Update';
  static const String close = 'Close';
  static const String billTo = 'Bill To';
  static const String paymentInformation = 'Payment Information';
  static const String bankName = 'Bank Name';
  static const String accountName = 'Account Name';
  static const String accountNo = 'Account No';
  static const String addItem = 'Add Item';
  static const String sno = 'S.NO';
  static const String item = 'Item';
  static const String qty = 'Qty';
  static const String rate = 'Rate';
  static const String rs = 'Rs.';
  static const String unit = 'Unit';
  static const String selectUnit = 'Select Unit';
  static const String selectItem = 'Select Item';
  static const String amount = 'Amount';
  static const String actions = 'Actions';
  static const String total = 'Total';
  static const String colon = ':';
  static const String noItems = 'No items found';
  static const String saveAsPdf = 'Save as PDF';
  static const String success = 'Success';
  static const String pdfSavedAt = 'PDF saved at';
  static const String failure = 'Failure';
  static const String pdfSavingDenied = 'PDF Saving Operation Denied';
  static const String warning = 'Warning';
  static const String itemCannotBeEmpty = 'Item cannot be empty';
  static const String quantityMustBeGreaterThanZero =
      'Quantity must be greater than zero';
  static const String rateMustBeGreaterThanZero =
      'Rate must be greater than zero';
}
